# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: "Tianyu Zhang"
subtitile: "Version 0.0"
name: "Tianyu Zhang"
repository: "shahuiz/shahuiz.github.io"
email: shahuiz@outlook.com
description: Welcome to my personal site! 
url: "https://shahuiz.github.io" 
baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Socials
# social:
#   type: Person  # Person or Organization (defaults to Person)
#   name: # If the user or organization name differs from the site's name
#   links:
#     - "https://twitter.com/corey_d_white"
# twitter_username: corey_d_white
# twitter:
#   username: "corey_d_white"
# github_username: shahuiz


# Displaying author info
author:
  name: "Tianyu Zhang"
  avatar: "/assets/images/gbta.jpeg"
  bio: "*PhD at Nanyang Technological University*" # Note: Markdown is allowed
  location: "Singapore"
  links:
  #  - label: "Website"
   #   icon: "fas fa-fw fa-link"
  #    url: "https://stefaniejfischer.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tianyu005@e.ntu.edu.sg"
    - label: "IACR"
      icon: "fab fa-fw fa-google"
      url: "https://www.iacr.org/cryptodb//data/author.php?authorkey=12897"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/corey_d_white"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shahuiz"

# Displaying website footer info
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tianyu005@e.ntu.edu.sg"
    - label: "IACR"
      icon: "fab fa-fw fa-google"
      url: "https://www.iacr.org/cryptodb//data/author.php?authorkey=12897"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/corey_d_white"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shahuiz"

# Default layouts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

  
include:
 - _pages

atom_feed:
  hide: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/